fix
Rabinzon/readquran.ru pull request #1
Opened 2023-01-02 13:50 UTC by Kopekbalik

@media(max-width:500px) {
  .main-list ol {
    column-count: 2;
    column-gap: 15vw;
  }
  }

2023-01-02 13:57 UTC, Rabinzon requested changes

2023-01-02 13:57 UTC, Rabinzon commented on public/main.css
> +  }
отступы поправь

2023-01-02 13:59 UTC, Kopekbalik commented on view/layouts/application.pug
> +              a.nav-link(href='http://free-quran.ru/') Коран в подарок
какое послание ?

2023-01-02 15:20 UTC, Kopekbalik reviewed
кароче , сделал

2023-01-02 17:57 UTC, Rabinzon commented on public/main.css
> +    max-width: 644px;
@Kopekbalik вот где ширину контейнера ограничил

2023-01-03 07:42 UTC, Kopekbalik reviewed
убрал подчеркивание
изменил радиус
задал больше столбиков
восстановил ширину

2023-01-03 07:43 UTC, Rabinzon commented on view/layouts/application.pug
>              li.nav-item
тоже удалить

2023-01-03 13:29 UTC, Rabinzon approved these changes

2023-01-03 13:29 UTC, merged